### ISSUE TITLE
Create an index_view to render Index.html and create the URL 

### ISSUE THREAD

**Issue by SameeranB** [IEEE-VIT/Django_To_Do#5]
Create an index_view in `Main/views.py` that returns the `Index.html` and create the URL for the same in `Main/urls.py`

**Comment by fsabr** [comment]
I'll take this up.

**Comment by fsabr** [comment]
Do I have to make the index.html ?

**Comment by SameeranB** [comment]
That is a separate issue, we just need to create a view to render it in this issue. The HTML file name will be `Index.html`. Do name the view: `index_view`

> Do I have to make the index.html ?
